### ISSUE TITLE
High CPU usage when running in background

### ISSUE THREAD

**Issue by interpretor** [AdguardTeam/AdGuardForSafari#210]
### Steps to reproduce

1. Start Adguard for Safari
2. Close Window

### Expected behavior
Adguard for Safari should not have any noticeable CPU usage when running in background

### Actual behavior
Adguard for Safari uses about 3 - 5% on a Quad-Core i7

### Your environment

* AdGuard for Safari version: 1.4.1
* Environment name and version: Safari 12.1.2 (14607.3.9)
* Operating System: macOS Mojave 10.14.6
* Filters you use in AdGuard: Default
* Any other browser extensions you have installed: -

**Comment by ameshkov** [comment]
@Mizzick any idea how we can troubleshoot this?

Obviously, we cannot reproduce this so I guess the only way would be to start writing a log file & introduce logging level

**Comment by Mizzick** [comment]
We actually do write the log file.
This file could be found `~/Library/Logs/<app name>/log.log`

**Comment by interpretor** [comment]
This problem exists on multiple macOS devices including Macbook Pro and Mac mini, so it should be reproducible on your side.

**Comment by ameshkov** [comment]
@interpretor could you please try the standalone build just in case?
https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.4.1

**Comment by cactus** [comment]
If I run dtruss against the pid, I get lots of repeated stat64 reads for files in a subdir named `app.asar`, which do not exist. `app.asar` appears to be an electron archive type.

Viewing/extracting with npm `asar` module shows contents, and so it doesn't seem corrupted. Not sure why it isn't working as expected. Maybe an electron bug?

Some sample dtruss output (repeats over and over and over):

```
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/app/utils/log.js\0", 0x70000630CE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/ui/images/triangle.svg\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/ui/js/i18n/i18n-helper.js\0", 0x70000630CE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/utils/i18n.js\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/ui/images/tick.svg\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
psynch_mutexdrop(0x11107AC80, 0x47F6F00, 0x47F6F00)		 = 0 0
psynch_cvwait(0x11107ACC0, 0x163200001632400, 0x1632000)		 = 0 0
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/README.md\0", 0x700007312E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/locales/ja.json\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
kevent(0x8, 0x7FFEE43CA720, 0x0)		 = 1 0
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/safari-ext/package.json\0", 0x700007312E00, 0x0)		 = -1 Err#20
dtrace: error on enabled probe ID 2174 (ID 159: syscall::read:return): invalid kernel access in action #12 at DIF offset 68
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/safari-ext/build/safari_ext_addon.target.mk\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
dtrace: error on enabled probe ID 2172 (ID 161: syscall::write:return): invalid kernel access in action #12 at DIF offset 68
psynch_mutexdrop(0x11107ADA0, 0x19D4700, 0x19D4700)		 = 0 0
psynch_mutexwait(0x11107ADA0, 0x19D4702, 0x19D4600)		 = 27084547 0
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/safari-ext/build/Makefile\0", 0x700005B09E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/locales/zh-cn.json\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/filters/filter_mobile_8.txt\0", 0x700007312E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/locales/ru.json\0", 0x700005B09E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/ui/images/logo-shield.svg\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/app/storage\0", 0x700005B09E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/ui/js/libs/ace\0", 0x700007312E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/app/storage/rules-storage.js\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/updater.js\0", 0x700005B09E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/safari-ext/build/Release\0", 0x700007312E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/safari-ext/shared/CommonLib/Lang/Logger/Lumberjack/DDLogMacros.h\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/app/app.js\0", 0x700005B09E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/safari-ext/shared/CommonLib/Lang/NSDate+Utils.h\0", 0x700007312E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/app/filters/filters-update.js\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/config/default.json\0", 0x700005B09E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/app/utils/i18n.js\0", 0x700007312E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/ui/css/main.css\0", 0x700005B09E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/locales/pt-pt.json\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/safari-ext/yarn.lock\0", 0x700007312E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/safari-ext/shared/CommonLib/Lang/Logger/Lumberjack/DDLegacyMacros.h\0", 0x700005B09E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/filters/filter_6.txt\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/ui/images/checked.svg\0", 0x700007312E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/tasks\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/filters/filter_10.txt\0", 0x700005B09E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/filters/filter_2.txt\0", 0x700007312E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/safari-ext/shared/CommonLib/Lang/ACLFileLogger.h\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/src/main/app/filters\0", 0x700005B09E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/safari-ext/shared/CommonLib/Lang/Logger/Lumberjack/DDFileLogger.h\0", 0x700007312E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/filters/filter_9.txt\0", 0x700005B09E00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/safari-ext/shared/CommonLib/Lang\0", 0x700006B0FE00, 0x0)		 = -1 Err#20
stat64("/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/safari-ext/shared/CommonLib/Lang/Logger/Lumberjack/DDAbstractDatabaseLogger.h\0", 0x700005B09E00, 0x0)		 = -1 Err#20
```

**Comment by cactus** [comment]
Also, no logs in `~/Library/Logs`. There is a log file in `~/Library/Containers/com.adguard.safari.AdGuard/Data/Library/Logs` named `log.log`, but the contents seem to be only updated when filters are updated, and there appears to be no correlation with the cpu issue in question (eg. last filter update was hours ago, and no log entries in that file since then).

**Comment by amok-san** [comment]
FWIW the beta from 3 days before doesn't show this behavior.

**Comment by ameshkov** [comment]
Well, this must have something to do with the sandbox that is used in the Mac App Store build. Standalone build is different.

**Comment by amok-san** [comment]
OK, but what do I have to do to get the final release from github running?

It crashes upon opening and says:
Termination Reason:    DYLD, [0x5] Code Signature

**Comment by interpretor** [comment]
> OK, but what do I have to do to get the final release from github running?
> 
> It crashes upon opening and says:
> Termination Reason: DYLD, [0x5] Code Signature

I also would be interested in an answer to this question. The final release crashes upon startup.

**Comment by Mizzick** [comment]
@amok-san @interpretor the release is fixed, thanks for your attention

**Comment by jwchong** [comment]
Hi,
Using Max App Store version and background CPU usage problem still there. Any fixes? Thanks.

**Comment by cpgn** [comment]
Hi,
AdGuard for Safari version 1.4.1 downloaded via App Store still showing the same behaviour.
Will there be a fix?
Cheers

**Comment by ameshkov** [comment]
We don't understand yet why there is such a difference between the AppStore and the standalone build. Once v1.5 is released on AppStore, we'll revisit this issue. Hopefully, it'll happen next week.

**Comment by ameshkov** [comment]
Hi everyone, we've just released v1.5 to MAS: https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.5.4

Could you please check if the issue is still present?

**Comment by cpgn** [comment]
It's fixed for me! Well done, guys

**Comment by ameshkov** [comment]
Awesome, thanks for testing it!

**Comment by ameshkov** [comment]
:(

**Comment by ameshkov** [comment]
@interpretor I wonder what's the difference between @cpgn configurations.

What MacOS versions do you have?

**Comment by interpretor** [comment]
Ignore my previous post. It seems fixed now!
A reboot worked wonders here.

**Comment by ameshkov** [comment]
🎉🎉🎉 

@interpretor thank you:)

**Comment by cactus** [comment]
Fixed here also! :heart:
