### ISSUE TITLE
Twitter promoted posts sneaking through, fixed with disable/enable

### ISSUE THREAD

**Issue by anastenko** [AdguardTeam/AdGuardForSafari#630]
@sporkman commented on [Wed Jun 30 2021](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1829)

### Issue Details

- **AdGuard version:**
  - AdGuard for Safari Version 1.9.19
- **Browser and version:**
  - Safari 14.1.1
- **Operating system and version:**
  - OS-X 10.14.6
- **Filters you use in AdGuard:**
  - All of the stock filters and no others
- **Stealth Mode settings**
  - : N/A
- **Other browser extensions:**
  -  1Password
 
### Expected Behavior

Promoted Tweets on Twitter are blocked

### Actual Behavior

Promoted Tweets are not blocked UNLESS I visit twitter, deselect "enabled on this website" in the AdGuard browser bar menu, then reselect "enabled on this website". The page reloads on reselecting and at that point promoted tweets are blocked again. If I close the tab and visit again, promoted ads will show until I repeat this process of disable/enable.

### Screenshots

N/A

### Additional Information

I have restarted my mac, restarted safari, and adguard.

**Comment by sporkman** [comment]
Here's another datapoint regarding the on/off toggling of AdGuard for Twitter.com:

- Visit the site, disable AdGuard for the site
- Close the tab
- Open a new tab, visit Twitter.com
- Promoted tweets are shown
- Enable AdGuard, page refreshes
- Promoted tweets are still shown
- Disable AdGuard, re-enable AdGuard
- Promoted tweets are again blocked

Seems interesting that if the starting state is disabled, the single toggle to "enabled" doesn't fix it, but "enable/disable/enable" does.

**Comment by anastenko** [comment]
@sporkman Hello.
Please check this behavior in version 1.10.4. It should have been fixed.

**Comment by sporkman** [comment]
Just updated, still seeing promoted tweets. Latest AdGuard and Safari Version 14.1.2 (14611.3.10.1.5).

I'll do some more checking, restart Safari, maybe reboot and circle back here...

![Screen Shot 2021-08-03 at 2 20 35 PM](https://user-images.githubusercontent.com/510750/128066479-48c50445-6450-4875-9370-32e18571fd5a.png)
![Screen Shot 2021-08-03 at 2 19 05 PM](https://user-images.githubusercontent.com/510750/128066481-f9c41b0f-1466-4f47-a289-1406edbeca21.png)

**Comment by sporkman** [comment]
Still getting promoted tweets after restarting safari. Same behavior - if I open a tab, load twitter disable adguard, and then enable it things are blocked. If I just open a tab and load, promoted tweets show.

**Comment by tvinzz** [comment]
@sporkman, do yo use v1.10.4?
Please try to remove cached data for twitter.com in Safari browser settings and the problem should gone.

**Comment by sporkman** [comment]
I think it's working now, but man, did I have to go nuts on clearing things out. First tried the simple "Develop -> Empty Caches", then various force-reload, then clearing all the local storage (not the cache proper) that's only available in the web inspector, and still no good. When I went in the inspector and repeated that, along with removing all cookies, that seems to have done it. Honestly don't get how the cookie-cleaning fixed it.

Attaching a snapshot of the local storage that was cleared, for the benefit of anyone having a similar issue.

Oops, spoke too soon. Opened a tab to get a screenshot and was greeted by a promoted tweet.

Same thing works - if I disable AdGuard, then re-enable it, blocking works.

Anything I can provide for troubleshooting? Safari is Version 14.1.2 (14611.3.10.1.5), OS is 10.14.6, AdGuard is 1.10.4 and filters were updated before I did all this testing.

<img width="748" alt="Screen Shot 2021-08-05 at 3 39 38 PM" src="https://user-images.githubusercontent.com/510750/128411181-7985f4c0-b614-45ca-bd36-06678449de9b.png">
<img width="765" alt="Screen Shot 2021-08-05 at 3 42 03 PM" src="https://user-images.githubusercontent.com/510750/128411183-564b0fad-732d-4821-b96b-bcc4ccafa3af.png">

**Comment by tvinzz** [comment]
@sporkman, thank you for your report.
Can you please export logs and settings, it will help us to fix the problem.

**Comment by sporkman** [comment]
Sure, is there any sensitive information in the settings or logs? Generally I don't publicly post any logs that I don't really know the contents of or what PII is in there. I'd be fine with somehow directly providing them.

**Comment by anastenko** [comment]
@sporkman You can send it to apple@adguard.com. Nobody is going to see it, except for our developers. Make sure to mention this ticket's number in your email.

**Comment by sporkman** [comment]
Need anything else? Still happening most of the time, still fixed with the "off/on" trick. Weird stuff!

**Comment by apricot23** [comment]
Issue has persisted for me, as well.

**Comment by sporkman** [comment]
I'll note that Macheist is offering deals on the paid version (https://www.macheist.com/brands/adguard), but this issue lingering for so long is kind of souring me on moving to paid.

**Comment by Birbber** [comment]
@sporkman Sent a test build on your mail. Please try it.

**Comment by sporkman** [comment]
I've got it in place and it seems good so far. I'd like to give it a day or two though to be sure...

**Comment by Birbber** [comment]
@sporkman Sure, let us know the result later on.

**Comment by sporkman** [comment]
Spoke too soon. Promoted tweets tarted leaking through again. I have the logging enabled in the adguard settings, so attaching what's in the console (lots of noise though about the ".map" files). Restarted adguard (and verified w/ps that it really was stopped), restarted safari, cleared cache ("Develop -> Empty Caches"). Will be restarting the mac in a bit to see if that does anything.

Anything I can gather for you?

Also the trick of disabling and re-enabling adguard still works.
<img width="841" alt="Screen Shot 2021-09-23 at 2 06 28 PM" src="https://user-images.githubusercontent.com/510750/134561322-fdc66772-21a6-4b14-9658-bcae175c442e.png">
<img width="1182" alt="Screen Shot 2021-09-23 at 2 06 50 PM" src="https://user-images.githubusercontent.com/510750/134561340-33737de8-6b90-47de-b2db-f7efa5b73070.png">
<img width="1189" alt="Screen Shot 2021-09-23 at 2 07 06 PM" src="https://user-images.githubusercontent.com/510750/134561360-bba13950-5f0b-425a-8c03-f7bc84b2e933.png">

**Comment by sporkman** [comment]
Rebooted, restarted, etc. and still happening... Anything else to look at? Can you folks reproduce?

I can try testing on a new user account if you think that might help. I'm also hanging back on 10.14 due to some 32-bit apps I need, could the OS version be an issue?

**Comment by Birbber** [comment]
@sporkman It seems our developers detected the issue. Will try to fix it with the next release.
Thanks for your patience.

**Comment by sporkman** [comment]
Any updates?

**Comment by sporkman** [comment]
Also, just bought AdGuard Mac, and sadly that seems to let even more promoted tweets through... :(

**Comment by windwak3r** [comment]
I couldn't reproduce the problem. Please leave a comment if the issue is still relevant.

**Comment by sporkman** [comment]
It's been working fine for a long time, forgot about this issue. I'm guessing maybe one of the filter updates way back when resolved it? I can't even remember the last time a promoted post came through my feed, thanks to whoever fixed whatever!
